# GNU Make solution makefile autogenerated by Premake
# Usage: make [ config=config_name ]
# Where {config_name} is one of: "debug", "release".

ifndef config
  config=debug
endif
export config

PROJECTS := OrcPFD

.PHONY: all clean $(PROJECTS)

all: $(PROJECTS)

OrcPFD: 
	@echo ==== Building OrcPFD ====
	@${MAKE} --no-print-directory -C . -f orcpfd.make

clean:
	@${MAKE} --no-print-directory -C . -f orcpfd.make clean

